# Generated by Django 4.0.6 on 2024-11-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_counts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
