# Generated by Django 4.0.6 on 2024-11-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_counts',
        ),
    ]
