# Generated by Django 4.0.6 on 2024-12-14 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_detectionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionrecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='detectionrecord',
            name='detected_at',
        ),
        migrations.AddField(
            model_name='detectionrecord',
            name='detected_hour',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='detectionrecord',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
